Repository moodlehq/moodleapp, pull requests merged in 2023-10, with the labels that each got.

#3801 Mobile 4362
  scripts/langindex.json
  src/addons/mod/scorm/services/scorm-sync.ts
  src/core/components/infinite-loading/infinite-loading.ts
  src/core/constants.ts
  src/core/features/contentlinks/services/contentlinks-helper.ts
  src/core/features/course/classes/activity-prefetch-handler.ts
  src/core/features/course/services/log-helper.ts
  src/core/features/course/services/module-delegate.ts
  src/core/features/fileuploader/services/fileuploader.ts
  src/core/features/settings/services/settings-helper.ts
  src/core/features/siteplugins/services/siteplugins-helper.ts
  src/core/services/app.ts
  src/core/services/file.ts
  src/core/services/filepool.ts
  src/core/services/utils/dom.ts
  src/core/services/utils/text.ts
  src/core/services/utils/utils.ts
  src/core/services/ws.ts
  src/core/singletons/window.ts
Labels: release

#3803 MOBILE-4362 grades: Fix swipe navigation in tablet
  src/core/features/grades/pages/course/course.page.ts
Labels: release

#3806 Mobile 4362
  src/addons/mod/wiki/pages/edit/edit.ts
  src/addons/storagemanager/pages/courses-storage/courses-storage.html
  src/core/features/reportbuilder/components/report-summary/report-summary.html
  src/core/features/settings/pages/licenses/licenses.html
Labels: release

#3807 Mobile 4362
  scripts/langindex.json
  src/addons/mod/data/components/action/action.ts
  src/core/components/combobox/combobox.scss
  src/core/components/context-menu/context-menu.ts
  src/core/components/user-avatar/user-avatar.scss
  src/core/features/block/components/block/block.scss
  src/core/features/course/components/module-completion/core-course-module-completion.html
  src/core/features/course/components/module-completion/module-completion.ts
  src/core/features/course/components/module/module.scss
  src/core/features/login/tests/behat/signup.feature
  src/core/features/settings/pages/general/general.html
  src/core/features/user/pages/about/about.html
  src/core/features/user/pages/about/about.scss
  src/core/features/user/pages/about/about.ts
  src/core/features/user/pages/profile/profile.html
  src/core/features/user/pages/profile/profile.scss
  src/core/features/user/pages/profile/profile.ts
  src/core/features/user/services/user-helper.ts
  src/core/features/user/tests/behat/snapshots/test-basic-usage-of-user-features-view-profile_21.png
  src/core/lang.json
  src/core/services/utils/dom.ts
  src/theme/theme.base.scss
Labels: release, wait for acceptance

#3811 Mobile 4348
  src/addons/mod/resource/components/index/addon-mod-resource-index.html
  src/addons/mod/resource/components/index/index.scss
  src/addons/mod/resource/components/index/index.ts
  src/addons/mod/resource/services/handlers/module.ts
  src/addons/mod/resource/services/resource-helper.ts
  src/addons/mod/resource/services/resource.ts
  src/theme/theme.base.scss
Labels: wait for acceptance

#3809 Mobile 4362
  local_moodleappbehat/tests/behat/behat_app_helper.php
  src/addons/mod/scorm/components/index/index.ts
  src/addons/mod/scorm/services/scorm.ts
  src/addons/mod/scorm/tests/behat/appearance_options.feature
  src/addons/mod/scorm/tests/behat/attempts_and_grading.feature
  src/addons/mod/scorm/tests/behat/availability.feature
  src/addons/mod/scorm/tests/behat/basic_usage.feature
  src/addons/mod/scorm/tests/behat/snapshots/test-appearance-options-of-scorm-activity-in-app-apply-width-and-height-when-using-new-window-mode_10.png
  src/addons/mod/scorm/tests/behat/snapshots/test-appearance-options-of-scorm-activity-in-app-apply-width-and-height-when-using-new-window-mode_16.png
  src/addons/mod/scorm/tests/behat/snapshots/test-appearance-options-of-scorm-activity-in-app-apply-width-and-height-when-using-new-window-mode_22.png
  src/core/classes/site.ts
Labels: release, wait for acceptance

#3812 Revert "MOBILE-4339 quiz: Add unanswered questions warning"
  scripts/langindex.json
  src/addons/mod/quiz/lang.json
  src/addons/mod/quiz/pages/player/player.ts
  src/addons/mod/quiz/tests/behat/basic_usage-311.feature
  src/addons/mod/quiz/tests/behat/basic_usage-39.feature
  src/addons/mod/quiz/tests/behat/basic_usage.feature
  src/addons/mod/quiz/tests/behat/quiz_navigation.feature
  src/theme/theme.base.scss
Labels: wait for acceptance

#3813 MOBILE-4407 url: Use Url parsing to determine last file
  src/core/directives/external-content.ts
  src/core/services/utils/url.ts
Labels: wait for acceptance

#3816 MOBILE-4362: Fix Drag & Drop race condition
  src/addons/qtype/ddimageortext/classes/ddimageortext.ts
  src/core/singletons/dom.ts
Labels: release, wait for acceptance

#3817 Mobile 4362
  src/addons/mod/glossary/services/handlers/index-link.ts
  src/addons/mod/lesson/pages/user-retake/user-retake.scss
  src/core/components/message/message.html
  src/core/features/comments/pages/viewer/viewer.html
  src/core/features/comments/pages/viewer/viewer.ts
Labels: release, wait for acceptance

#3818 Mobile 4362
  .github/workflows/release.yml
  src/addons/mod/workshop/components/index/addon-mod-workshop-index.html
  src/addons/mod/workshop/components/index/index.ts
  src/addons/mod/workshop/components/submission/addon-mod-workshop-submission.html
  src/addons/mod/workshop/services/workshop.ts
  src/core/components/mod-icon/mod-icon.scss
  src/core/features/settings/pages/licenses/licenses.html
  src/core/features/user/pages/about/about.scss
  src/core/features/user/tests/behat/snapshots/test-basic-usage-of-user-features-view-profile_21.png
  src/theme/theme.base.scss
Labels: release, wait for acceptance

#3820 MOBILE-4069 behat: Fix view events behat failing in some cases
  src/addons/mod/scorm/tests/behat/basic_usage.feature
Labels: wait for acceptance

#3821 MOBILE-4362 collapsible: Do not collapse headers if inside a tab outlet
  src/core/directives/collapsible-header.ts
Labels: release

#3823 MOBILE-4362 activitymodules: Fix activity modules block icons
  src/addons/block/activitymodules/components/activitymodules/activitymodules.ts
Labels: release, wait for acceptance

#3822 MOBILE-4428 quiz: Fix adaptive behaviour
  src/addons/mod/quiz/tests/behat/quiz_behaviour.feature
  src/addons/mod/quiz/tests/behat/quiz_navigation.feature
  src/core/features/question/components/question/core-question.html
  src/core/features/question/services/question-helper.ts
Labels: wait for acceptance

#3824 MOBILE-3371 search: Remove top results
  src/core/features/search/classes/global-search-results-source.ts
  src/core/features/search/services/global-search.ts
Labels: wait for acceptance

#3825 Mobile 4362
  src/core/components/infinite-loading/infinite-loading.ts
  src/core/features/course/components/course-format/course-format.html
  src/core/features/course/components/course-format/course-format.ts
  src/core/features/course/components/module/core-course-module.html
  src/core/features/course/components/module/module.ts
  src/core/features/course/pages/contents/contents.ts
  src/core/features/course/pages/list-mod-type/list-mod-type.html
  src/core/features/course/pages/list-mod-type/list-mod-type.ts
  src/core/features/course/pages/module-preview/module-preview.html
  src/core/features/course/tests/behat/basic_usage-311.feature
  src/core/features/course/tests/behat/basic_usage.feature
  src/core/features/course/tests/behat/snapshots/test-basic-usage-of-one-course-in-app-view-course-contents_46.png
  src/core/features/course/tests/behat/snapshots/test-basic-usage-of-one-course-in-app-view-course-contents_50.png
  src/theme/theme.base.scss
Labels: release, wait for acceptance

#3828 MOBILE-4362 core: Improve autoFocus animation
  src/core/directives/auto-focus.ts
Labels: release

#3833 Mobile 4362
  src/addons/storagemanager/pages/course-storage/course-storage.html
  src/addons/storagemanager/pages/courses-storage/courses-storage.html
  src/core/features/siteplugins/components/plugin-content/plugin-content.ts
Labels: release

#3832 Mobile 4362
  src/core/features/course/components/module/module.scss
  src/theme/theme.dark.scss
Labels: release

#3834 MOBILE-3371 search: Improve course search
  src/addons/block/globalsearch/services/block-handler.ts
  src/core/features/search/components/global-search-filters/global-search-filters.component.ts
  src/core/features/search/components/global-search-filters/global-search-filters.html
  src/core/features/search/pages/global-search/global-search.html
  src/core/features/search/pages/global-search/global-search.ts
  src/core/features/search/tests/behat/global-search.feature
Labels: wait for acceptance

#3835 MOBILE-4362 quiz: Fix wrong renderization of ddwtos in some cases
  src/addons/qtype/ddwtos/classes/ddwtos.ts
Labels: release, wait for acceptance

#3837 Mobile 4362
  src/addons/mod/glossary/services/glossary.ts
  src/addons/mod/workshop/services/workshop.ts
  src/addons/mod/workshop/tests/behat/basic_usage.feature
Labels: release

#3838 Mobile 4362
  src/addons/block/activitymodules/components/activitymodules/activitymodules.scss
  src/addons/messages/pages/discussion/discussion.html
  src/addons/messages/pages/discussion/discussion.ts
  src/addons/mod/lti/services/handlers/module.ts
  src/addons/mod/resource/services/handlers/module.ts
  src/addons/mod/url/services/handlers/module.ts
  src/core/components/mod-icon/mod-icon.scss
  src/core/components/mod-icon/mod-icon.ts
  src/core/components/user-avatar/core-user-avatar.html
  src/core/components/user-avatar/user-avatar.scss
  src/core/components/user-avatar/user-avatar.ts
  src/core/features/course/services/module-delegate.ts
  src/core/features/grades/pages/course/course.scss
  src/core/features/login/tests/behat/snapshots/test-basic-usage-of-login-in-app-add-a-new-account-in-the-app--site-name-in-displayed-when-adding-a-new-account_13.png
  src/core/features/mainmenu/components/user-menu-button/user-menu-button.scss
  src/core/features/question/services/question-helper.ts
  src/core/features/rating/services/rating.ts
  src/core/features/search/components/global-search-result/global-search-result.scss
  src/core/features/user/pages/about/about.ts
  src/core/features/user/services/user.ts
  src/core/services/utils/url.ts
  src/theme/theme.base.scss
  src/theme/theme.dark.scss
  src/theme/theme.light.scss
Labels: release, wait for acceptance

#3841 Mobile 4362
  src/addons/block/myoverview/components/myoverview/myoverview.ts
  src/addons/mod/assign/components/submission/submission.ts
  src/core/components/recaptcha/core-recaptcha.html
  src/core/components/recaptcha/recaptcha.ts
  src/core/features/block/classes/base-block-component.ts
  src/core/features/login/pages/credentials/credentials.ts
  src/core/features/login/pages/email-signup/email-signup.html
  src/core/features/login/pages/email-signup/email-signup.ts
  src/core/features/login/tests/behat/snapshots/test-basic-usage-of-login-in-app-add-a-new-account-in-the-app--site-name-in-displayed-when-adding-a-new-account_9.png
  src/core/features/settings/pages/general/general.html
  src/core/features/settings/pages/general/general.ts
  src/core/services/analytics.ts
Labels: release, wait for acceptance
