Repository moodlehq/moodleapp, pull requests merged in 2024-01, with the labels that each got.

#3887 Mobile 3947
  .github/workflows/acceptance.yml
  .github/workflows/performance.yml
  scripts/langindex.json
  src/addons/block/timeline/components/timeline/addon-block-timeline.html
  src/addons/block/timeline/lang.json
  src/addons/block/timeline/tests/behat/basic_usage.feature
  src/addons/calendar/components/calendar/calendar.ts
  src/addons/calendar/pages/day/day.ts
  src/addons/calendar/tests/behat/create_events.feature
  src/addons/competency/tests/behat/navigation.feature
  src/addons/messages/tests/behat/basic_usage.feature
  src/addons/mod/glossary/tests/behat/navigation.feature
  src/addons/mod/quiz/tests/behat/basic_usage.feature
  src/addons/mod/survey/tests/behat/basic_usage.feature
  src/addons/notifications/pages/list/list.html
  src/addons/notifications/tests/behat/notifications.feature
  src/addons/userprofilefield/datetime/component/addon-user-profile-field-datetime.html
  src/core/components/combobox/core-combobox.html
  src/core/components/context-menu/core-context-menu-popover.html
  src/core/components/input-errors/input-errors.ts
  src/core/components/swipe-slides/swipe-slides.ts
  src/core/features/login/tests/behat/signup.feature
  src/core/features/mainmenu/tests/behat/mainmenu.feature
  src/testing/services/behat-dom.ts
  src/testing/services/behat-runtime.ts
  src/theme/theme.base.scss
Labels: wait for acceptance, Ionic7

#3890 Mobile 3947
  gulp/dev-config.js
  gulp/git.js
  gulp/jira.js
  gulp/task-push.js
  gulp/url.js
  gulp/utils.js
  gulpfile.js
  package-lock.json
  package.json
  src/addons/block/myoverview/components/myoverview/addon-block-myoverview.html
  src/addons/block/myoverview/components/myoverview/myoverview.scss
  src/addons/block/tags/components/tags/tags.scss
  src/addons/block/timeline/components/timeline/addon-block-timeline.html
  src/addons/mod/forum/tests/behat/snapshots/test-basic-usage-of-forum-activity-in-app-reply-a-post_9.png
  src/core/components/combobox/combobox.scss
  src/core/components/combobox/combobox.ts
  src/core/components/combobox/core-combobox.html
  src/core/features/fileuploader/services/handlers/album.ts
  src/core/features/fileuploader/services/handlers/audio.ts
  src/core/features/fileuploader/services/handlers/camera.ts
  src/core/features/fileuploader/services/handlers/file.ts
  src/core/features/fileuploader/services/handlers/video.ts
  src/core/features/sharedfiles/services/handlers/upload.ts
  src/core/features/user/services/handlers/profile-mail.ts
  src/theme/theme.base.scss
Labels: wait for acceptance, Ionic7

#3886 MOBILE-3947: Fix behat tests
  .github/workflows/acceptance.yml
  local_moodleappbehat/tests/behat/behat_app.php
  src/addons/calendar/pages/event/event.ts
  src/addons/competency/pages/competency/competency.page.ts
  src/addons/messages/tests/behat/basic_usage.feature
  src/addons/mod/assign/pages/submission-review/submission-review.ts
  src/addons/mod/feedback/pages/attempt/attempt.ts
  src/addons/mod/forum/pages/discussion/discussion.ts
  src/addons/mod/forum/pages/new-discussion/new-discussion.ts
  src/addons/mod/glossary/pages/entry/entry.ts
  src/addons/mod/glossary/tests/behat/navigation.feature
  src/addons/notifications/pages/notification/notification.ts
  src/app/app-routing.module.ts
  src/core/classes/items-management/list-items-manager.ts
  src/core/classes/items-management/routed-items-manager.ts
  src/core/classes/items-management/swipe-navigation-items-manager.ts
  src/core/features/grades/pages/course/course.page.ts
  src/core/features/mainmenu/mainmenu-tab-routing.module.ts
  src/core/features/reminders/components/date/date.html
  src/core/features/reminders/components/set-button/set-button.html
  src/core/features/reminders/components/set-button/set-button.ts
  src/core/features/reminders/tests/behat/activity_reminders.feature
  src/core/features/reminders/tests/behat/course_reminders.feature
  src/core/features/user/pages/profile/profile.ts
  src/testing/services/behat-dom.ts
  src/testing/services/behat-runtime.ts
Labels: wait for acceptance, Ionic7

#3894 MOBILE-3947 core: Fix wrong types for chooser plugin
  src/core/features/native/plugins/chooser.ts
  src/types/cordova-plugin-chooser.d.ts
Labels: Ionic7

#3896 MOBILE-4490 android: Fix crash in Android 5.1 and 6 due to StatusBar
  package-lock.json
  package.json
Labels: Ionic7

#3901 MOBILE-4470 behat: Fix snapshots
  src/core/features/login/tests/behat/snapshots/test-basic-usage-of-login-in-app-add-a-new-account-in-the-app--site-name-in-displayed-when-adding-a-new-account_13.png
Labels: release, wait for acceptance

#3903 MOBILE-3947 travis: Update linux distribution to Jammy
  .github/workflows/acceptance.yml
  .github/workflows/merge.yml
  .github/workflows/mirror.yml
  .github/workflows/performance.yml
  .github/workflows/release.yml
  .github/workflows/update_behat_plugin.yml
  .travis.yml
Labels: Ionic7

#3908 MOBILE-3947 behat: Fix close popup step
  src/testing/services/behat-runtime.ts
Labels: wait for acceptance, Ionic7

#3912 MOBILE-3947 ionic: Reimport mixins due to :dir rule problems
  src/theme/helpers/ionic.components.mixins.scss
  src/theme/helpers/ionic.functions.color.scss
  src/theme/helpers/ionic.functions.string.scss
  src/theme/helpers/ionic.mixins.scss
Labels: wait for acceptance, Ionic7

#3913 MOBILE-3947 login: Restore logo fallback
  src/core/features/login/pages/credentials/credentials.html
  src/core/features/login/pages/reconnect/reconnect.html
Labels: Ionic7

#3915 Mobile 4173
  local_moodleappbehat/fixtures/dummy.pdf
  scripts/langindex.json
  src/core/classes/element-controllers/FrameElementController.ts
  src/core/components/iframe/core-iframe.html
  src/core/components/iframe/iframe.ts
  src/core/directives/format-text.ts
  src/core/lang.json
  src/core/services/utils/dom.ts
  src/core/services/utils/iframe.ts
  src/core/services/utils/utils.ts
  src/tests/behat/open_files.feature
Labels: wait for acceptance

#3916 MOBILE-4173 behat: Don't hardcode webserver in embedded PDF test
  src/tests/behat/open_files.feature
Labels: wait for acceptance
